##########################################
#                                        #
#             BuildUHC 1.0               #
#         Created by DoSantos_           #
#                                        #
##########################################




###################################################
#               Scoreboard Section                #
###################################################


Scoreboard: #CONFIGURE SCOREBOARD
  Title: '   &5&lBuild&d&lFFA   '

ScoreboardText:
  - '&dKills: &9%kills%'
  - '&dDeaths: &9%deaths%'
  -

###################################################
#               Spawn Section                     #
###################################################

SpawnLocation:
  World: world
  X: -101
  Y: 71
  Z: 264
  Pitch: 0
  Yaw: 0
